import { MD3LightTheme, MD3DarkTheme } from "react-native-paper";

const brandColors = {
  primary: "#6200EE",
  primaryContainer: "#E8DEF8",
  secondary: "#03DAC6",
  secondaryContainer: "#CCE8E4",
  accent: "#FF0266",
  success: "#4CAF50",
  warning: "#FFC107",
  error: "#B00020",
  info: "#2196F3",
};

export const lightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: brandColors.primary,
    primaryContainer: brandColors.primaryContainer,
    secondary: brandColors.secondary,
    secondaryContainer: brandColors.secondaryContainer,
    error: brandColors.error,
    background: "#F8F9FA",
    surface: "#FFFFFF",
    surfaceVariant: "#F1F3F5",
    onPrimary: "#FFFFFF",
    onPrimaryContainer: "#21005D",
    onSecondary: "#000000",
    onSecondaryContainer: "#00201E",
    onBackground: "#1C1B1F",
    onSurface: "#1C1B1F",
    onSurfaceVariant: "#49454F",
    outline: "#79747E",
    success: brandColors.success,
    warning: brandColors.warning,
    info: brandColors.info,
    card: "#FFFFFF",
    border: "#E0E0E0",
  },
  roundness: 12,
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  typography: {
    fontFamily: "System",
    h1: { fontSize: 32, fontWeight: "bold" },
    h2: { fontSize: 24, fontWeight: "bold" },
    h3: { fontSize: 20, fontWeight: "600" },
    body: { fontSize: 16, fontWeight: "normal" },
    caption: { fontSize: 12, color: "#666" },
  },
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: "#BB86FC",
    primaryContainer: "#3700B3",
    secondary: "#03DAC6",
    secondaryContainer: "#012C28",
    error: "#CF6679",
    background: "#121212",
    surface: "#1E1E1E",
    surfaceVariant: "#2C2C2C",
    onPrimary: "#000000",
    onPrimaryContainer: "#E8DEF8",
    onSecondary: "#000000",
    onSecondaryContainer: "#CCE8E4",
    onBackground: "#E3E3E3",
    onSurface: "#E3E3E3",
    onSurfaceVariant: "#CAC4D0",
    outline: "#938F99",
    success: "#81C784",
    warning: "#FFD54F",
    info: "#64B5F6",
    card: "#1E1E1E",
    border: "#333333",
  },
  roundness: 12,
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  typography: {
    fontFamily: "System",
    h1: { fontSize: 32, fontWeight: "bold" },
    h2: { fontSize: 24, fontWeight: "bold" },
    h3: { fontSize: 20, fontWeight: "600" },
    body: { fontSize: 16, fontWeight: "normal" },
    caption: { fontSize: 12, color: "#999" },
  },
};
